### ISSUE TITLE
[Feature Request] Close Popper when you hover over it with mouse

### ISSUE THREAD

**Issue by martinszeltins** [valgeirb/vue-popper#32]
Right now there is no way to tell Popper to close when you hover over it with mouse. Sometimes it is useful when there are buttons behind popper and you can't click on them because popper is in front of them.

This is an issue only when you set the mode to hover=true

It would be nice to have an option to hide it on hover like this

````
<Popper :hover="true" :closeOnHover="true">
    ....
</Popper>
````

**Comment by valgeirb** [comment]
You can do `<Popper hover :interactive="false" content="This Popper is not interactive" />`

Would that solve your issue?

**Comment by martinszeltins** [comment]
> :interactive="false"

Thanks, this did the trick for me!
