### ISSUE TITLE
Upgrading to Vue 3.2.x breaks the Popper component

### ISSUE THREAD

**Issue by Flippeey** [valgeirb/vue-popper#39]
Hi, great work on the library I am enjoying it! I was using Vue-3-popper v1.2.1 and Vue 3.1.2 and it works fine, but when I try to upgrade Vue to 3.2.x and Vue-3-popper to 1.3.0 I get strange runtime errors that I cannot explain. Hoping you can help me fix it.

These are the 2 errors I see, which prevents my entire view from loading.

![chrome_DwHM3UmnKa](https://user-images.githubusercontent.com/5073998/136357661-ba9b5583-5d9a-4136-8ae9-ad798f5ba5fc.png)
![chrome_FJRmWgK4gv](https://user-images.githubusercontent.com/5073998/136357666-b97148fe-ed87-4b1a-a656-83c2ef2613b6.png)

I've followed the documentation and made my own wrapper component for the Popper component. 
I use it like this in my view: 
`
<PopoverIcon	class="d-inline-flex" :content="$tc('contractOverview.table.contractExpirationWarning', {								count: item.data.remainingDays})"><i class="pi pi-exclamation-circle" /></PopoverIcon>`
However, when I try to upgrade to Vue 3.2 even the sample component does not work for me. I think it could be related to the slot property, but seeing as even the example does not work I don't know how to fix it. Any idea what could be causing this?

**Comment by valgeirb** [comment]
I believe this works and it's also simpler looking.

I updated [the docs](https://valgeirb.github.io/vue3-popper/guide/getting-started.html#how-can-i-wrap-popper-with-my-own-component).
