### ISSUE TITLE
Bug on Vue3.0.4.

### ISSUE THREAD

**Issue by xApep** [valgeirb/vue-popper#63]
**Description of the bug**
I have installed package and tested with example in the docs, but I always get this error:
![image](https://user-images.githubusercontent.com/1315340/170115506-b86a54a6-ce61-4272-bee5-4f0458b0b954.png)

**Comment by valgeirb** [comment]
Can you try updating to `vue@3.2.x` and see if that solves your problem?

**Comment by xApep** [comment]
@valgeirb thank you, it does solve the problem. Is there any other way around with not updating?

**Comment by valgeirb** [comment]
No I don't think so, I think this error is because Popper uses [v-bind in CSS](https://vuejs.org/api/sfc-css-features.html#v-bind-in-css) that was introduced in `vue@3.2.x` - you should be able to upgrade your Vue dependency without any problems though.
